environment:
  matrix:
    - nodejs_version: "8"

init:
  # debugging Appveyor build. More info:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.symlinks true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - yarn

environment:
    SB_HC_NAMESPACE:
    SB_HC_KEYRULE:
    SB_HC_KEY:
    SB_HC_PATH:

cache:
  - node_modules
  - .eslintcache
  - "%LOCALAPPDATA%\\Yarn"

test_script:
  - yarn jest --color --runInBand

# Don't actually build.
build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false